search_enabled: true
remote_theme: pmarsceill/just-the-docs

company_name: FrRog
settings:
  name: Your Name
  username: yourusername
  email: name@yourdomain.com
  password: YourPassword
  pop:
    server: mail.frrog.com
    port: 143
  imap:
    server: mail.frrog.com
    port: 993
  smtp:
    server: mail.example.com
    port: 587
